FROM test-2:latest AS build
WORKDIR /usr/src/app
COPY . .
RUN npm run build 
FROM test-1 as prod
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/dist ./dist
RUN chown node:node -R /usr/src/app/dist
USER node
CMD ["node","dist/main"]



